%% ****************************************************************
%
%           Description : generate a simulated trajectory
%                           
%
%           Author : G.M. Hoang
%
%           Rev. 0 : baseline
%
%           Inputs : 
%                       - simParams : struct containing simulation parameters 
%                       - profile : struct containing profile parameters
%           Outputs : 
%                       - signals : struct containing all signals generated by simulation
%
% *************************************************************

function [signals] = ZEN_generateDeterministicTrajectory(simParams, profile)

% intialize simulation signals
[signals] = ZEN_initializeSignals(simParams);

signals.position = simParams.loadedTrajectory.position;

